i-am-balancer/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'pages#home'

  get '/about', to: 'pages#about'

  get '/contact', to: 'pages#contact'

  get '/shop', to: 'pages#shop'

  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

i-am-balancer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

i-am-balancer/app/models/blog.rb
class Blog < ApplicationRecord
end

i-am-balancer/app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

i-am-balancer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

i-am-balancer/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :post_owner, only: [:edit, :update, :destroy, :toggle_status]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end


    def post_owner
      unless current_user.roles.include?(:user)
        flash[:notice] = 'Access denied as you are not owner of this Post'
        redirect_to blogs_path
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

i-am-balancer/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def shop
  end
end

i-am-balancer/app/helpers/application_helper.rb
module ApplicationHelper
end

i-am-balancer/app/helpers/blogs_helper.rb
module BlogsHelper
end

i-am-balancer/app/helpers/pages_helper.rb
module PagesHelper
end

i-am-balancer/app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

i-am-balancer/app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

i-am-balancer/app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">
<h1 class="col-lg-12">Blogs and Recipes!</h1>
<div class="col-md-4 wider">
  <%= image_tag "berries.jpg", width: 340, alt: "profile image", class: 'profile-img' %>
</div>
<div class="col-md-4 wider">
  <%= image_tag "smooth.jpg", width: 340, alt: "profile image", class: 'profile-img' %>
</div>
<div class="col-md-4 wider">
  <%= image_tag "meaty.jpg", width: 340, alt: "profile image", class: 'profile-img' %>
</div>

<table class="littleless col-lg-12">
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <hr>
        <td class="body"><%= link_to 'Show', blog %></td>
        <td class="noshow"><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td class=""><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <br>
    <% end %>
  </tbody>
</table>

<br>


</div>
</div>

i-am-balancer/app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

i-am-balancer/app/views/blogs/show.html.erb
<body>
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>
<br>
<%= link_to 'Back', blogs_path %>
</div> 
</div>
</body>

i-am-balancer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I Am Balance</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>
  <nav class="navbar navbar-light bg-light">
  <a class="navbar-brand"><%= image_tag "Logo_edited-1.jpg", width: 80, height: 80, alt: "profile image", class: 'nav-img' %> </a>

  <ul class="nav col-sm-5">
  <li class="nav-item">
    <a class="nav-link" href="/">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/about">About Me</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/contact">Contact</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/blogs">Blog</a>
  </li>
</ul> 
</nav>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
  </div>
  </body>
  <footer>
    <p><i class="far fa-copyright"></i>2018 I am Balance  All Rights Reserved</p>
  </footer>
</html>

i-am-balancer/app/views/pages/about.html.erb
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>

      <div class="container">
      <div class="row">
        <div class="col-lg-7">
            <%= image_tag "IMG_3919.JPG",  alt: "profile image", class: 'profile-img' %>
        </div>
        <div class="col-lg-5" id="spaceit">
           <h4> I help empower people to overcome their fears and learn self acceptance and happiness within. Health is connected to all areas of your life: exercise, learning, career, romance, speed of life, cooking, community, spirituality, food, home, finances, and friendship. By balancing areas of your life, you will find that you are truly happy. You will also find your underlying fears that stop you from progressing to be the person you envisioned yourself being.</h4>
           <br>
           <p>I am a Master Health and Wellness Coach. I have degrees in Feng Shui, a Masters of Science in Psychology, Master of Herbology, Reiki Master, Art Therapy, Yoga Instructor. These degrees set me apart from other coaches; allowing me to use multiple modalities when needed. It also allows me to specialize in many areas. My main specialties are in nutrition, digestive/adrenal, and helping people overcome their fears. I do coaching for businesses, groups, individuals through skype and phone calls. </p>
        </div>
      </div>
      </div>
  </body>

i-am-balancer/app/views/pages/contact.html.erb
<body class="pickme">
<div class="container">
<div class="row">
        <h1 class="col-sm-6"> Questions?<br>Lets get in touch</h1>
        <div class="col-sm-6">
            <a class="btn" href="https://www.instagram.com/i_am_balance_/?hl=en"><i class="fab fa-instagram"></i></a>
            <a class="btn" href="https://www.facebook.com/iambalance17/"><i class="fab fa-facebook"></i></a>
            <a class="btn" href="https://twitter.com/kaemars"><i class="fab fa-twitter-square"></i></a>
        </div>

        <div class="col-sm-2 movedown">
        <i class="fas fa-envelope-square"></i>
        </div>  
        <div class="col-sm-10 movedown" id="centerit">
        <h5> kln.samadhi49@gmail.com </h5>
        </div>

        <div class="col-sm-2 movedown">
        <i class="fas fa-phone"></i>
        </div>  
        <div class="col-sm-10 movedown" id="centerit">
        <h5> 435-864-7850 </h5>
        </div>
</div>
</div>
</body>

i-am-balancer/app/views/pages/home.html.erb
<body>
<div class="container">
<div class="row">
  <div class="card mb-3">
    <img class="card-img-top" id="biggone"><%= image_tag "Flower_edited-1.JPG",  alt: "profile image", class: 'profile-img' %>
    <div class="card-body">
      <h5 class="card-title">I am Balance</h5>
      <p class="card-text"><q>I have taken the six week course with KaeLene. This was a fun and learning experience. KaeLene is very attentive in what she is doing, she is always there to help when you have a question. She takes more time to help you than others would. She wants to make sure that you get all the help and advise that you need to help succeed. She gives you great motivation and daily encouragement.</q> </p>
      <br>
      <p><q>One of the things that KaeLene helped me with,is taking a few minutes every day for myself. I am trying hard to get my body to respond to the things that it needs, to get my thyroid in check and improve my health. I will try to stay on the path that she has helped me lay out for myself.</q> - Rayette Jones </p>
      <a href="/pages/about">
        <button class="btn btn-outline-primary">Find out more!</button>
      </a>
    </div>
  </div>

  <body class="homepage">
  <div class="card col-lg-12">
  <div class="card-body">
    <h2>I have helped these people find balance, and I will help you too!</h1>
  </div>
</div>

  <div class="col-lg-4">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">James Biorge - SAYVES</h5>
        <p class="card-text"> <q>In our busy and stressful lives (especially for women) finding balance in life can bring the positive energy levels from peace and contentment in life. </q></p>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Sonja Cazier -Energy Works</h5>
        <p class="card-text"><q>KaeLene is a very giften person with many talents. I have benefitted physically, mentally, and emotionally from her work. I trust her intuition and her knowledge.</q></p>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Business Executive and Family Man</h5>
        <p class="card-text">Doing the 6 week health challenge was an absolute life changer. It helped me not only learn about health, fitness, foods, and more, but also helped me balance my life as a whole. I began to feel balanced in my personal and professional life. It was such a neat experience to have a health coach with a fountain of knowledge who is also committed to helping you change your life for the better!</q></p>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Cheyenne Soares - Mom/Fitness Enthusiast</h5>
        <p class="card-text"><q>I have loved having you coach me each week! I especially loved that you really covered all areas of health and wellness, not only diet and fitness. I feel like so often I get busy and neglect my mental and emotional health, so it has been so nice to have you there to guide me to bettering myself that way. I have learned a lot of new things! The last 6 weeks have really made me stop and focus, and its amazing how when I take care of myself, I am so much happier, less stressed and able to accomplish so much more day to day! Thank you !!!</q></p>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Mark Graves - Wellevated Inc.</h5>
        <p class="card-text"><q>I would recommend KaeLene. I have known her for years. She is very talented. </q></p>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Nick Drishinski - Software Developer/Entrepreneur</h5>
        <p class="card-text"><q>If you are looking for someone who has all the knowledge you could want, and will put in the effort you NEED then KaeLene is your answer. She is the complete package. </q></p>
      </div>
    </div>
  </div>

</div>
</div>
</div>
</body>

i-am-balancer/app/views/pages/shop.html.erb
<h1>Pages#shop</h1>
<p>Find me in app/views/pages/shop.html.erb</p>